"""Delete_auto_publish_fields

Revision ID: 605123e9bd4b
Revises: ebd7e26de169
Create Date: 2025-11-26 23:34:21.659406

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "605123e9bd4b"
down_revision: Union[str, Sequence[str], None] = "ebd7e26de169"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "auto_publish")
    op.drop_column("posts", "aps_job_id_publish")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts",
        sa.Column(
            "aps_job_id_publish",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "posts",
        sa.Column("auto_publish", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
