"""Add content plan tables

Revision ID: 62562a1e0d82
Revises: 605123e9bd4b
Create Date: 2025-12-03 21:28:13.628533

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "62562a1e0d82"
down_revision: Union[str, Sequence[str], None] = "605123e9bd4b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "content_plans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("duration_days", sa.Integer(), nullable=False),
        sa.Column("posts_per_week", sa.Integer(), nullable=False),
        sa.Column("preferences", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.telegram_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_content_plans_created_at"),
        "content_plans",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_content_plans_user_id"), "content_plans", ["user_id"], unique=False
    )
    op.create_table(
        "content_plan_days",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content_plan_id", sa.Integer(), nullable=False),
        sa.Column("day_name", sa.String(length=10), nullable=False),
        sa.Column("date", sa.String(length=10), nullable=False),
        sa.Column("time", sa.String(length=10), nullable=False),
        sa.Column("post_type", sa.String(length=255), nullable=True),
        sa.Column("topic", sa.Text(), nullable=True),
        sa.Column("format", sa.String(length=255), nullable=True),
        sa.Column("week", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["content_plan_id"], ["content_plans.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_content_plan_days_content_plan_id"),
        "content_plan_days",
        ["content_plan_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_content_plan_days_content_plan_id"), table_name="content_plan_days"
    )
    op.drop_table("content_plan_days")
    op.drop_index(op.f("ix_content_plans_user_id"), table_name="content_plans")
    op.drop_index(op.f("ix_content_plans_created_at"), table_name="content_plans")
    op.drop_table("content_plans")
    # ### end Alembic commands ###
